version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "github-actions"]
    commit-message:
      prefix: "chore"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      minor-patch:
        update-types:
          - "patch"
          - "minor"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
    labels: ["dependencies", "gomod"]
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/examples/build"
    schedule:
      interval: "cron"
      cronjob: "0 9 * * *"
    labels: ["dependencies", "docker"]
    commit-message:
      prefix: "chore"
