---
version: "2"

formatters:
  enable:
    - gci

linters:
  default: all
  disable:
    - wsl  # Deprecated
    - varnamelen  # Too strict
    - exhaustruct  # Too strict
    - mnd  # Too strict
    - gomodguard  # Replaced by gomodguard_v2
  enable:
    - gomodguard_v2 
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - "$pkg:main"
          allow:
            - $gostd
            - g0efilter/internal/...
    goconst:
      ignore-tests: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/google/gopacket.Packet
